webapps/hitchhiker/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from hitchhiker import views as private_views
# import hitchhiker.url
urlpatterns = [
    url(r'^$', private_views.home, name='home'),
    url(r'^refreshPost', private_views.refreshPost, name='refreshPost'),
    url(r'^login', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout', auth_views.logout_then_login, name='logout'),
    url(r'^register', private_views.register, name='register'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', private_views.confirm_registration, name='confirm'),
    url(r'^post-ride', private_views.postRide, name='postRide'),
    url(r'^profile', private_views.viewProfile, name = 'viewProfile'),
    url(r'^place', private_views.viewPlace, name = 'viewPlace'),
    url(r'^process-acceptRide-request+', private_views.processAcceptRideRequest, name='processAcceptRequest'),
    url(r'^process-confirmRide-request+', private_views.processConfirmRideRequest, name='processConfirmRequest'),
    url(r'^editprofile', private_views.EditProfile, name='editprofile'),
    url(r'^process-ignoreMessage-request+', private_views.processIgnoreMessageRequest, name='processIgnoreMessageRequest'),
    url(r'^process-addFriend-request+', private_views.processAddFriendRequest, name='processAddFriendRequest'),
    url(r'^process-confirmFriend-request+', private_views.processConfirmFriendRequest, name='processConfirmFriendRequest'),
    url(r'^process-cancelRide-request+', private_views.processCancelRideRequest, name='processCancelRideRequest'),
]

webapps/webapps/urls.py
from django.conf.urls import include, url
from hitchhiker import views
from hitchhiker import views as private_views

# import hitchhiker.url
urlpatterns = [
    # Examples:
    # url(r'^$', 'webapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', private_views.home),
    url(r'^', include('hitchhiker.urls')),
]

webapps/hitchhiker/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Position(models.Model):
    gID = models.CharField(max_length = 255, primary_key=True)
    name = models.CharField(max_length = 255)
    imgUrl = models.CharField(max_length = 256,blank=True, null = True)
    address = models.CharField(max_length= 256, blank = True)
    longitude = models.FloatField()
    latitude = models.FloatField()
    hotness = models.IntegerField(default = 1)
    reviews = models.ManyToManyField('Review', blank = True, related_name = "position_reviews")
    def __unicode__(self):
        return self.name
class Review(models.Model):
    timeStamp = models.BigIntegerField()
    text = models.CharField(max_length = 1024)
    author = models.CharField(max_length = 30)
    rating = models.FloatField()
    text_length = models.IntegerField()
    def __unicode__(self):
        return self.text
#this class is just a message sent to user
class Message(models.Model):
    sender = models.ForeignKey('Profile', related_name = 'message_sender')

    text = models.CharField(max_length = 255)
    messageType = models.CharField(max_length = 30)
    # either driver or passenger, actually, every message is regarding a single ride posted
    rideType = models.CharField(max_length = 30)
    # the id of driver or passenger
    rideId = models.IntegerField()
    # active or inactive
    active = models.BooleanField()
    def __unicode__(self):
        return str(self.messageType) + ": " + str(self.text)


class Profile(models.Model):
    user = models.ForeignKey(User, related_name = 'profile_owner')
    lName = models.CharField(max_length = 30, blank = True, null = True)
    fName = models.CharField(max_length = 30, blank = True, null = True)
    age = models.IntegerField(default = 0, blank = True, null = True)
    shortBio = models.CharField(default = 'This man leaves nothing', max_length = 430, blank = True, null = True)
    email = models.CharField(max_length= 40, blank = True, null = True)
    friends = models.ManyToManyField('Profile', related_name = 'profile_friends', blank=True)
    pictureUrl = models.CharField(max_length = 256,blank=True, null = True)
    destinations = models.ManyToManyField(Position, related_name = 'profile_destinations', blank = True)
    messages = models.ManyToManyField(Message, related_name='profile_messages')
    def __unicode__(self):
        return self.fName + " " + self.lName

class Driver(models.Model):
    profile = models.ForeignKey(Profile, related_name = 'driver_profile')
    origin = models.ForeignKey(Position, related_name = 'driver_origin')
    destination = models.ForeignKey(Position, related_name = 'driver_destination')
    message = models.CharField(max_length = 256, blank = True)
    rideTime = models.IntegerField(blank = True)
    rideTimeStr = models.CharField(max_length = 255, blank = True)
    active = models.BooleanField(default = True, blank = True)
    def __unicode__(self):
        return "from " + str(self.origin) + " to " + str(self.destination)


class Passenger(models.Model):
    profile = models.ForeignKey(Profile, related_name = 'passenger_profile')
    origin = models.ForeignKey(Position, related_name = 'passenger_origin')
    destination = models.ForeignKey(Position, related_name = 'passenger_destination')
    message = models.CharField(max_length = 256, blank = True)
    rideTime = models.IntegerField(blank = True)
    rideTimeStr = models.CharField(max_length = 255, blank = True)
    active = models.BooleanField(default=True, blank = True)
    def __unicode__(self):
        return "from " + str(self.origin) + " to " + str(self.destination)

webapps/hitchhiker/forms.py
#!/usr/bin/python
from django import forms
from django.contrib.auth.models import User
from hitchhiker.models import *
from django.core.validators import validate_email, RegexValidator

"""
class AuthenticationForm(forms.Form):
	username = forms.CharField(
		max_length = 20,
		label='Username',
		validators = [RegexValidator(r'^[0-9a-zA-Z]*$',
					  message='Enter only letters and numbers')],
		widget=forms.TextInput(attrs={'class' : 'form-control', 
		  							  'placeholder' : 'Username',
		  							  }),
	)
	password = forms.CharField(
		max_length = 20,
		label='Password',
		widget=forms.PasswordInput(attrs={'class' : 'form-control', 
		  							   'placeholder' : "Your Password",
		  							  }),
	)
"""


class RegisterForm(forms.Form):
	firstname = forms.CharField(
		max_length = 20,
		label='First Name',
		required = False,
		widget=forms.TextInput(attrs={'class' : 'form-control', 
									  'placeholder' : 'First Name',
									  'id' : 'inputFirstName'
							          'autofocus',
									  }),
    )
	lastname = forms.CharField(
		max_length = 20,
		label='Last Name',
		required = False,
		widget=forms.TextInput(attrs={'class' : 'form-control', 
		  							  'placeholder' : 'Last Name',
		  							  'id' : 'inputLastName'
          							  'autofocus',
		  							  }),
    )
	email = forms.CharField(
		max_length = 50,
		validators = [validate_email],
		widget=forms.EmailInput(attrs={'class' : 'form-control', 
		  							  'placeholder' : 'Your Email',
		  							  'id' : 'inputEmail'
          							  'autofocus',
		  							  }),
	)
	
	username = forms.CharField(
		max_length = 20,
		label='Username',
		validators = [RegexValidator(r'^[0-9a-zA-Z]*$',
					  message='Enter only letters and numbers')],
		widget=forms.TextInput(attrs={'class' : 'form-control', 
		  							  'placeholder' : 'Username',
		  							  'id' : 'inputUsername'
          							  'autofocus',
		  							  }),
	)
	age = forms.IntegerField(
		label='Age',
		required = False,
		widget=forms.NumberInput(attrs={'class' : 'form-control', 
		  							   'placeholder' : '0',
										'min' : "0", 
										'max' : "200",
		  							   'id' : 'inputAge',
										}),
	)
	bio = forms.CharField(
		max_length = 430,
		label='Bio',
		required = False,
		widget=forms.Textarea(attrs={'class' : 'form-control', 
		  							   'placeholder' : "I'm a",
		  							   'id' : 'inputBio',
		  							  }),
		
	)
	password1 = forms.CharField(
		max_length = 20,
		label='Password',
		widget=forms.PasswordInput(attrs={'class' : 'form-control', 
		  							   'placeholder' : "Your Password",
		  							   'id' : 'inputPassword'
          							   'autofocus',
		  							  }),
	)
	password2 = forms.CharField(
		max_length = 20,
		label='Confirm Password',
		widget=forms.PasswordInput(attrs={'class' : 'form-control', 
		  							   'placeholder' : "Confirm Password",
		  							   'id' : 'confirmPassword'
          							   'autofocus',
		  							  }),
	)
	
	def clean(self):
		cleaned_data = super(RegisterForm, self).clean()
		password1 = cleaned_data.get('password1')
		password2 = cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords do not match.")
		
		userAge = cleaned_data.get('age')
		if (userAge < 0 or userAge > 150) and (userAge != None): #if use (userAge != None): NOT NULL constraint failed: socialnetwork_profile.age
			raise forms.ValidationError("Age is invalid.")
		return cleaned_data
	
	def clean_username(self):
		username = self.cleaned_data.get('username')
		if User.objects.filter(username__exact=username):                 # hren
			raise forms.ValidationError("Username is already taken.")
		return username
		
class EditProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		exclude = (
			'user',
			'friends',
			'pictureUrl',
			'destinations',
			'messages',
		)
		widgets = {'picture': forms.FileInput()} # prevent the user from deleting avater
	picture = forms.FileField(required=False, label='Change picture')
		
		
	def __init__(self, *args, **kwargs):
		super(EditProfileForm, self).__init__(*args, **kwargs)
		self.fields['lName'].label = 'Last Name'
		self.fields['lName'].widget = forms.TextInput(attrs={'class': "form-control"})
		self.fields['fName'].label = 'First Name'
		self.fields['fName'].widget = forms.TextInput(attrs={'class': "form-control"})
		self.fields['age'].widget = forms.NumberInput(attrs={'class': "form-control"})
		self.fields['shortBio'].label = 'Short Bio'
		self.fields['shortBio'].widget=forms.Textarea(attrs={'class': "form-control"})
		self.fields['email'].widget = forms.EmailInput(attrs={'class': "form-control"})
	
	def clean(self):
		cleaned_data = super(EditProfileForm, self).clean()
		userAge = cleaned_data.get('age')
		if (userAge < 0 or userAge > 200) and (userAge != None): # hren
			raise forms.ValidationError("Age is invalid.")
		userEmail = cleaned_data.get('email')
		if userEmail != '' and not '@' in userEmail:
			raise forms.ValidationError("")
		return cleaned_data

webapps/hitchhiker/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="This is the base for hitchhiker.">
		<meta name="author" content="hren">
		<!-- link rel="icon" href="../../favicon.ico" -->

		<title> {% block title %} {% endblock %} </title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">

		<!-- Custom styles for this template -->
		{% load staticfiles %}
		<link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet" type="text/css">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		{% block style %} {% endblock %}
	</head>

	<body>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../static/js/jquery.min.js"><\/script>')</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<!-- Fixed navbar -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand"> Hitchhiker </a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
				{% block header %}  {% endblock %}
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<!-- Begin page content -->
		{% block content %} {% endblock %}

		<footer class="footer">
			<div class="container">
				<center class="text-muted"> &copy; <script type="text/javascript">document.write(new Date().getFullYear());</script> Web Application Development Team10</center>
			</div>
		</footer>
        
        

		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../static/js/jquery.min.js"><\/script>')</script>
	</body>
</html>

webapps/hitchhiker/templates/confirmed.html
{% extends "base.html" %}

{% block title %} Hitchhiker -- Email Confirmed {% endblock %}

{% block style %}
{% load staticfiles %}
<link href="{% static 'css/register-confirm.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="container">
<div class="jumbotron">
	<h1>Registration Confirmed</h1>
	<p>Thank you for confirming your email address. Please <a href="{% url 'login' %}">login</a> to access your Hitchhiker.</p>
</div>
</div>
{% endblock %}

webapps/hitchhiker/templates/hitchhiker.html
{% extends "base.html" %}

{% block title %} Hitchhiker {% endblock %}

{% block style %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

{% load staticfiles %}

<link href="{% static 'css/hitchhiker.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/mainpage.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCTrA-MUhX0ibMppDDSq91rGC2rkj9fM8&libraries=places&callback=initMap"
async defer></script>

{% endblock %}

{% block header %}
<ul class="nav navbar-nav">
    <li class="active"><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'viewProfile' %}?username={{selfProfile.user.username}}">Profile</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Message&nbsp;
        <span class="badge" id="newMessageCount">{{newMessageCount}}</span></a>
        <ul class="dropdown-menu">
          {% for message in selfProfile.messages.all %}
            {% if message.active == True %}
              <div>
                <li role="separator" class="divider"></li>
                <li class="box">
                <p>{{message.text}}</p>
                <button class="btn btn-default btn-xs" onclick="sendIgnoreMessageRequest('{{message.id}}','{{message.sender.user.username}}','{{message.messageType}}','{{message.rideId}}','{{message.rideType}}', this)">Ignore</button>
                {% if message.messageType == "accept" %}
                  <button class="btn btn-primary btn-xs" onclick="sendConfirmRideRequest('{{message.sender.user.username}}','{{message.rideId}}','{{message.rideType}}','{{message.id}}', this)">Confirm</button>
                {% endif %}
                {% if message.messageType == "friendInvitation" %}
                  <button class="btn btn-primary btn-xs" onclick="sendConfirmFriendRequest('{{message.id}}', this)">Confirm</button>
                {% endif %}
                </li>
              </div>
            {% endif %}
          {% endfor %}
          </li>
        </ul>
      </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Friends&nbsp;
        <ul class="dropdown-menu">
          {% for friend in selfProfile.friends.all %}
          <div>
            <li role="separator" class="divider"></li>
            <li class="box">
              <a href="{% url 'viewProfile' %}?username={{friend.user.username}}">
                <img src="{{friend.pictureUrl}}" class="img-circle" alt="{{friend.fName}} {{friend.lName}}" width="50" height="50">
                <span>{{friend.fName}} {{friend.lName}}</span>
              </a>
            </li>
          </div>
        {% endfor %}
        </ul>
    </li>
    <li ><a href="{% url 'logout' %}">Log out</a></li>
</ul>
{% endblock %}

{% block content %}

    <div class="container">
    	<div id= "map"></div>
    	<input id="originInput" type="text" placeholder="Starting point" style="width:200px; margin:5px; autofocus;" name="startingPoint">
    	<input id="destinationInput" type="text" placeholder="Destination" style="width:200px; margin:5px; autofocus;" name="destination">
    	<!-- this button will actually pop out a window for further input -->
    	<button id="modal" type="button" style="width:80px; margin:5px; autofocus;" data-toggle="modal" data-target="#myModal" onclick="showInput()">post</button>

        <!-- Passengers -->
        <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" href="#collapse1">Passengers</a>
                </h4>
              </div>
              <div id="collapse1" class="panel-collapse collapse">
                    <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-2">Departure Time</th>
                            <th class="col-md-2">Starting Point</th>
                            <th class="col-md-2">Destination</th>
                            <th class="col-md-4">Rider</th>
                            <th class="col-md-2">Confirm</th>
                            <!-- this is just for develop -->
                        </tr>
                    </thead>
                        
                    <tbody id="passengerList">
                        {% for passenger in passengers %}
                        <tr>
                            <td class="d1">{{passenger.rideTimeStr}}</td>
                            <td class="d2">{{passenger.origin.name}}</td>
                            <td class="d3">{{passenger.destination.name}}</td>
                            <td class="d4">
                            <div class="user">
                                <a href="{% url 'viewProfile' %}?username={{passenger.profile.user.username}}">
                                <img src="{{passenger.profile.pictureUrl}}" class="img-circle" alt="{{passenger.profile.fName}} {{passenger.profile.lName}}" width="30" height="30">
                                <span>{{passenger.profile.fName}} {{passenger.profile.lName}}</span>
                                </a>
                                <div class="userInfo">
                                    <h5>{{passenger.profile.fName}} {{passenger.profile.lName}} says:</h5>
                                    <!-- add post message here -->
                                    <p> {{passenger.message}} </p>
                                </div>
                            </div>
                            </td>
                            <td class="d5"><button onclick="sendAcceptRideRequest('{{passenger.profile.user.username}}','{{passenger.id}}','Passenger')">Accept</button>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
              </div>
            </div>
        </div>
        <!-- Drivers -->
        <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" href="#collapse2">Drivers</a>
                </h4>
              </div>
              <div id="collapse2" class="panel-collapse collapse">
                            <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-2">Departure Time</th>
                            <th class="col-md-2">Starting Point</th>
                            <th class="col-md-2">Destination</th>
                            <th class="col-md-4">Rider</th>
                            <th class="col-md-2">Confirm</th>
                        </tr>
                    </thead>
                    <tbody id="driverList">
                        {% for driver in drivers %}
                        <tr>
                            <td class="d1">{{driver.rideTimeStr}}</td>
                            <td class="d2">{{driver.origin.name}}</td>
                            <td class="d3">{{driver.destination.name}}</td>
                            <td class="d4">
                            <div class="user">
                                <a href="{% url 'viewProfile' %}?username={{driver.profile.user.username}}">
                                <img src="{{driver.profile.pictureUrl}}" class="img-circle" alt="{{driver.profile.fName}} {{driver.profile.lName}}" width="30" height="30">
                                <span>{{driver.profile.fName}} {{driver.profile.lName}}</span>
                                </a>
                                <div class="userInfo">
                                    <h5>{{driver.profile.fName}} {{driver.profile.lName}} says:</h5>
                                    <!-- add post message here -->
                                    <p> {{driver.message}}</p>
                                </div>
                            </div>
                            </td>
                            <td class="d5"><button class="btn btn-default btn-s" onclick="sendAcceptRideRequest('{{driver.profile.user.username}}','{{driver.id}}','Driver')">Accept</button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
              </div>
            </div>
        </div>
    </div> <!-- end of class="container" -->
	
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Post Ride</h4>
				</div>
				<div class="modal-body">
					
					<label>Starting Point:</label>
					<p><span id='startingPoint'></span></p><br>
					<label>Destination:</label>
					<p><span id='destination'></span></p><br>
					<label>Time:</label>
					<input id="rideTimeInput" type="datetime-local" name="departureTime"><br><br>
					<label>Type:</label>
					<select id = "rideTypeSelect">
					  <option value ="Driver">Driver</option>
					  <option value ="Passenger">Passenger</option>
					</select>
					<br><br>
					<label for="id_message">Message:</label>
					<textarea class="form-control" id="id_message" name="message" placeholder="Hey, " autofocus maxlength="255"></textarea><br>
					
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button id="post" type="button" class="btn btn-primary" data-dismiss="modal" onclick="postRide()">Post</button>
				</div>
			</div>
		</div>
	</div>
	<!-- end of modal -->

	<!-- important for popover, put it at the end -->
	{% load staticfiles %}
	<script src="{% static 'js/popoverLoop.js' %}"></script>

{% endblock %}

webapps/hitchhiker/templates/register.html
{% extends "base.html" %}

{% block title %} Hitchhiker -- Login {% endblock %}
{% block style %} <link href="../static/css/signin.css" rel="stylesheet"> {% endblock %}


{% block content %}
	<div class="container">

	<form class="form-signin" id="id_registration" method="post" action="{% url 'register' %}">
		{% csrf_token %}
		<h1 class="form-signin-heading">Please sign up</h1>
		
		<label for="id_firstname" class="sr-only">First Name</label>
		<input class="form-control" id="id_firstname" name="firstname" type="text" placeholder="First Name" autofocus><br>
		<p style="color: red"> {{ form.firstname.errors }}</p>
		
		<label for="id_lastname" class="sr-only">Last Name</label>
		<input class="form-control" id="id_lastname" name="lastname" type="text" placeholder="Last Name" autofocus><br>
		<p style="color: red"> {{ form.lastname.errors }}</p>
		
		<label for="id_email" class="sr-only">Email Address</label>
		<input class="form-control" id="id_email" name="email" type="email" placeholder="Email Address" required autofocus><br>
		<p style="color: red"> {{ form.email.errors }}</p>
		
		<label for="id_username" class="sr-only">Username</label>
		<input class="form-control" id="id_username" name="username" type="text" placeholder="Username" required autofocus><br>
		<p style="color: red"> {{ form.username.errors }}</p>
		
		<label for="id_age" class="sr-only">Age</label>
		<input class="form-control" id="id_age" name="age" type="number" placeholder="Your Age" min="0" max="200" autofocus><br>
		<p style="color: red"> {{ form.age.errors }}</p>
		
		<label for="id_registration" class="sr-only">Bio</label>
		<textarea class="form-control" id="id_registration" name="bio" placeholder="I'm a" form="id_registration" autofocus></textarea><br>
		<p style="color: red"> {{ form.bio.errors }}</p>
		
		<label for="id_password1" class="sr-only">Your Password</label>
		<input class="form-control" id="id_password1" name="password1" type="password" placeholder="Your Password" required autofocus>
		<p style="color: red"> {{ form.password1.errors }}</p>
		
		<label for="id_password2" class="sr-only">Confirm Password</label>
		<input class="form-control" id="id_password2" name="password2" type="password" placeholder="Confirm Password" required autofocus>
		<p style="color: red"> {{ form.password2.errors }}</p>

		{% for field in form.hidden_fields %}
		{{field}}
		{% endfor %}
		<br>
		<a href="{% url 'login' %}" class="btn btn-lg btn-danger"> Cancel </a>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<button type="submit" class="btn btn-lg btn-primary" value="Register">Sign up</button>
		<br><br>
		{% for error in form.non_field_errors %}
			<p style="color: red">{{error}}</p>
		{% endfor %}
	</form>
	</div> <!-- /container -->
{% endblock %}